// <auto-generated />
using System;
using GeradorDeFolha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeradorDeFolha.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231028175129_CriandoTabelaCadastroModel")]
    partial class CriandoTabelaCadastroModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeradorDeFolha.Models.CadastroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdmissaoData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AtualizacaoData")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CadastroData")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<double>("SalarioB")
                        .HasColumnType("double");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CadastroModel");
                });
#pragma warning restore 612, 618
        }
    }
}
